### ISSUE TITLE
In vxms spring demo dependency should be changed

### ISSUE THREAD

**Issue by armdev** [amoAHCP/vxms#24]
Hello,

I changed spring-ext dependency version and group id and it build success.

`<dependency>
            <groupId>org.jacpfx.vertx.spring</groupId>
            <artifactId>vertx-spring-ext</artifactId>
            <version>2.2</version>
        </dependency>`

Also changed  repositories:
 <repositories>
        <repository>
            <id>sonatype-nexus-staging</id>
            <url>
                https://oss.sonatype.org/service/local/staging/deploy/maven2
            </url>
        </repository>
and
        <repository>
            <id>sonatype-nexus-snapshots</id>
            <url>
                https://oss.sonatype.org/content/repositories/snapshots
            </url>
        </repository>
    </repositories>

Old dependency failed during a build.

**Comment by amoAHCP** [comment]
fixed in https://github.com/amoAHCP/vxms/commit/7e73e77448d5a79cae7825e8aa4d4f1c7529c78b

THX

**Comment by armdev** [comment]
Thanks too .
