### ISSUE TITLE
Proposal: Make functionality in VxmsEndpoint also usable without inheritance.

### ISSUE THREAD

**Issue by atsticks** [amoAHCP/vxms#4]
To improve interoperability with other Vertx extensions/existing code I would appreciate to have the functionality implemented by `VxmsEndpoint` also usable without inheritance, e.g. by providing a instantiable form of `VxmsEndpoint` that can be added as ordinary Java field in an owning verticle, or that can be deployed as a verticle on its own by its owning verticle.

**Comment by amoAHCP** [comment]
Nice idea, I had a prototype using vertx factory, but than you have to declare the factory and you'll get conflicts with other extensions. But something like: VxmsEndpoint.init(this); should work

**Comment by amoAHCP** [comment]
done in https://github.com/amoAHCP/vxms/commit/e681a3c861f9d6fa0d860310f4eebfc8ce3c559e
